epochs: 10
resume: None
learning_rate: 0.001
weight_decay: 10e-6
inference_device: 'cuda'

train:
  batch_size: 4
  num_workers: 4
  valid_size: 0.3
  train_path: './dataset/medium_sample/train'

test:
  batch_size: 4
  num_workers: 4
  test_path: './dataset/medium_sample/test'

model:
  base_model: 'my_model_class_1'